language: node_js

node_js:
- node

addons:
  apt:
    packages:
    - xvfb

install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- nvm install 7
- npm install -g yarn xvfb-maybe
- yarn

before_script:
- npm build

script:
- xvfb-maybe npm test

deploy:
  skip_cleanup: true
  provider: npm
  email: philipp.sperber+npmjs@gmail.com
  api_key:
    secure: qF098sz/BdFlaI2Hm080/UIRcgGtNIsG4eARxUhryL+rg+LwxOzgFGqqSGB61EvD5LndtNqFMf1rn/7h69vUc3idKZ6kYwm+LkMJlusJPgjT29mswYvkUNdEBRSjpvexom2qJ0u9aFjqizVdL+ykcl7un/bDB6zMxv5iTi9U6zM5ZXS15zjTCZiwSSVykKId26G/EvSJgoEa5py47Di+oCBKJlZ/+y6t3WXueLfpot4cLqrqI11/FMahn3lmI3rQJoqxMfiRctMHTajRkTtDKgFJhl8R1XjW7RAlviZFSEVLxy3piLHHSQZM1yMgvcBTCtYR/1sM8L4mPjKdiMXV/u+xc62daHr5r/MVhe6bqFAqcgmJVcUaJiAg9d2hrhQksTnBFH2N0UBBvxq/ezP+Jyb9HOMGAFFlEOFsUtvgjs/3F2oOgm5xNfFXzXACD5hTcDQVi/FOZWZn5eFtDgNj9dnImwHf8pjGkrLTMMLIb+bpy7B11WjQTLYneEW3uXpO4DbJRTpPlPuLVQnRA52TCu7p/jmx7+fh5dluvei9h7Nfn4ujXVgASMpjwX9YIV4GUrQJEKb4t3gNmXAVDiW62PghDPf51RXW/jo7qcnVvgOkZdkT2zdrt48dGWg8HnCKAd81b7Er4QlOoAw5W+EUfYpiNY7DmvMhOmWP7HIra0A=
  on:
    tags: true
    repo: psperber/redux-persist-electron-storage
